source 'https://rubygems.org'

gem 'bootstrap', '~> 4.0.0.alpha5'
gem 'cocoon', '~> 1.2', '>= 1.2.9'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'puma', '~> 3.0'
gem 'rails', '~> 5.0.1'

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'

gem 'jbuilder', '~> 2.5'
gem 'turbolinks', '~> 5'

gem 'haml-rails', '~> 0.9'

gem 'kaminari', '~> 0.17.0'
gem 'nokogiri'

source 'https://rails-assets.org' do
  gem 'rails-assets-tether', '>= 1.1.0'
end

group :development, :test do
  gem 'byebug', platform: :mri
end

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
